app = "asddsa"
kill_signal = "SIGINT"
kill_timeout = 5
[build]
[env]
PORT = "8080"
[experimental]
auto_rollback = true
# If you want to specify internal_port, add this section:
# [http_service]
# internal_port = 8080

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 256
