[Version]
Class=IEXPRESS
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
RebootMode=NoRestart
TargetName=%TEMP%\ProtonUI.exe
FriendlyName=Proton UI Launcher
AppLaunched=Launch-ProtonUI.bat
PostInstallCmd=<none>
InstallPrompt=
DisplayLicense=
FinishMessage=
[Strings]
[SourceFiles]
SourceFiles0=.
[SourceFiles0]
File1=Launch-ProtonUI.bat
File2=ProtonUI.html
File3=Run-Proton-HWID-Spoofer.bat
File4=tools\HWID-Spoofer.ps1
